services: 
  frontend: 
    container_name: frontend
    build: ./front_end/weather-dashboard
    ports: 
      - "5173:5173"
    depends_on: 
      - backend
    restart: always
  
  backend: 
    container_name: backend
    build: 
      context: ./back_end/weatherBackend
      dockerfile: weatherBackend/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: Host=database;Port=5432;Database=${db_name};Username=${db_user};Password=${db_password}
      Jwt__Secret: ${JWT_SECRET}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__ExpirationInMinutes: ${JWT_EXPIRATION}
    ports: 
      - "8080:8080"
    depends_on:
      database: 
        condition: service_healthy
    restart: always
  
  database: 
    container_name: database
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s 
      retries: 5
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=${db_user}
      - POSTGRES_PASSWORD=${db_password}
      - POSTGRES_DB=${db_name}