services: 
  frontend: 
    container_name: frontend
    build: ./front_end/weather-dashboard
    ports: 
      - "5173:5173"
    depends_on: 
      - backend
    restart: always
  
  backend: 
    container_name: backend
    build: 
      context: ./back_end/weatherBackend
      dockerfile: weatherBackend/Dockerfile
    
    ports: 
      - "8000:8000"
    depends_on:
      db: 
        condition: service_healthy
    restart: always
  
  db: 
    container_name: db
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s 
      retries: 5
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=${db_user}
      - POSTGRES_PASSWORD=${db_password}
      - POSTGRES_DB=${db_name}