services: 
  frontend: 
    container_name: frontend
    build: ./front_end/weather-dashboard
    ports: 
      - "5173:5173"
    depends_on: 
      - backend
    restart: always
  
  backend: 
    container_name: backend
    build: ./back_end/weatherBackend/weatherBackend
    ports: 
      - "8000:8000"
    depends_on:
      db: 
        condition: service_healthy
    restart: always
  
  db: 
    container_name: db
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s 
      retries: 5
    ports: 
      - "5432:5432"